"""Generated by scripts/generate_honesty_stems.py; do not edit."""

from typing import Final

EN_STEMS: Final = (
    "probabilit",
    "P(",
    "chance",
    "likelihood",
    "odds",
    "quantile",
    "spread",
    "percentage",
    "tail",
)
TR_STEMS: Final = (
    "olas\u0131l",
    "ihtimal",
    "\u015fans",
    "y\u00fczde",
    "kantil",
    "yay\u0131l\u0131m",
    "kuyruk",
)
