"""Recommending a squad for a real, upcoming deadline.

Everything here reads a captured snapshot rather than a live endpoint: capture is a
deliberate step in a script, and what arrives here is bytes that were written down. That
is what lets a past recommendation be rebuilt exactly, and what keeps every test offline.
"""

from squadopt.live.calibration import (
    HISTORICAL_CAPTAIN_OPTIMISM,
    HISTORICAL_XI_OPTIMISM_PER_STARTER,
    INTERVAL_RULE_VERSION,
    LIVE_CALIBRATION_CONTRACT_VERSION,
    GameweekCalibrationRow,
    LiveCalibrationError,
    LiveCalibrationResult,
    calibration_markdown,
    measure_live_calibration,
)
from squadopt.live.horizon import (
    FIXTURE_SCALING_RULE_VERSION,
    HORIZON_POST_PROCESSING_CONTRACT_VERSION,
    build_projection_horizon,
    gameweek_fixture_fingerprints,
    make_projection_horizon_builder,
)
from squadopt.live.ledger import (
    SEASON_LEDGER_CONTRACT_VERSION,
    LedgerEntry,
    LedgerError,
    extract_event_points,
    ledger_summary,
    load_entry,
    load_ledger,
    record_decision,
    record_outcome,
    summary_markdown,
)
from squadopt.live.recommendation import (
    CONTROL_MODEL_NAME,
    CONTROL_MODEL_VERSION,
    OPENING_FEATURE_CONTRACT_VERSION,
    SUPPORTED_TARGET_GAMEWEEK,
    Projection,
    RecommendationInputs,
    infer_season,
    project,
    read_inputs,
)
from squadopt.live.report import (
    REPORT_CONTRACT_VERSION,
    SQUAD_COLUMNS,
    Recommendation,
    build_recommendation,
    projection_fingerprint,
    render,
)
from squadopt.live.risk import (
    LIVE_RISK_CONTRACT_VERSION,
    LiveResidualHistory,
    LiveRiskBlocker,
    LiveRiskDiagnostics,
    LiveRiskStatus,
    LiveRiskValidationError,
    evaluate_live_risk,
    risk_not_requested,
)
from squadopt.live.rules import (
    CHIP_NAMES,
    SEASON_RULES_CONTRACT_VERSION,
    ChipWindow,
    ScoringRules,
    SeasonRules,
    SeasonRulesError,
    TransferRules,
    read_season_rules,
    render_rules,
    rules_to_dict,
)

__all__ = [
    "CHIP_NAMES",
    "CONTROL_MODEL_NAME",
    "CONTROL_MODEL_VERSION",
    "FIXTURE_SCALING_RULE_VERSION",
    "HISTORICAL_CAPTAIN_OPTIMISM",
    "HISTORICAL_XI_OPTIMISM_PER_STARTER",
    "HORIZON_POST_PROCESSING_CONTRACT_VERSION",
    "INTERVAL_RULE_VERSION",
    "LIVE_CALIBRATION_CONTRACT_VERSION",
    "LIVE_RISK_CONTRACT_VERSION",
    "OPENING_FEATURE_CONTRACT_VERSION",
    "REPORT_CONTRACT_VERSION",
    "SEASON_LEDGER_CONTRACT_VERSION",
    "SEASON_RULES_CONTRACT_VERSION",
    "SQUAD_COLUMNS",
    "SUPPORTED_TARGET_GAMEWEEK",
    "ChipWindow",
    "GameweekCalibrationRow",
    "LedgerEntry",
    "LedgerError",
    "LiveCalibrationError",
    "LiveCalibrationResult",
    "LiveResidualHistory",
    "LiveRiskBlocker",
    "LiveRiskDiagnostics",
    "LiveRiskStatus",
    "LiveRiskValidationError",
    "Projection",
    "Recommendation",
    "RecommendationInputs",
    "ScoringRules",
    "SeasonRules",
    "SeasonRulesError",
    "TransferRules",
    "build_projection_horizon",
    "build_recommendation",
    "calibration_markdown",
    "evaluate_live_risk",
    "extract_event_points",
    "gameweek_fixture_fingerprints",
    "infer_season",
    "ledger_summary",
    "load_entry",
    "load_ledger",
    "make_projection_horizon_builder",
    "measure_live_calibration",
    "project",
    "projection_fingerprint",
    "read_inputs",
    "read_season_rules",
    "record_decision",
    "record_outcome",
    "render",
    "render_rules",
    "risk_not_requested",
    "rules_to_dict",
    "summary_markdown",
]
