"""Joint point scenarios and fixed-decision distribution summaries."""

from squadopt.scenarios.decision_scoring import (
    COMPONENT_DECISION_LOWER_QUANTILE,
    COMPONENT_DECISION_READOUT_CONTRACT_VERSION,
    COMPONENT_DECISION_SCORING_CONTRACT_VERSION,
    ComponentDecisionDistributionReadout,
    ComponentDecisionScoringResult,
    score_component_scenario_decision,
    summarize_component_decision_distribution,
)
from squadopt.scenarios.evaluation import (
    RivalSquad,
    ScenarioComparisonResult,
    compare_fixed_decisions,
    evaluate_fixed_decision,
    wilson_interval,
)
from squadopt.scenarios.generator import generate_scenarios, validate_residual_history
from squadopt.scenarios.models import (
    RESIDUAL_HISTORY_COLUMNS,
    SCENARIO_CONTRACT_VERSION,
    SCENARIO_EVALUATION_CONTRACT_VERSION,
    SCENARIO_OPTIMIZATION_CONTRACT_VERSION,
    ScenarioConfig,
    ScenarioConfigurationError,
    ScenarioError,
    ScenarioEvaluationConfig,
    ScenarioEvaluationResult,
    ScenarioOptimizationConfig,
    ScenarioOptimizationResult,
    ScenarioRiskMetrics,
    ScenarioSet,
    ScenarioTarget,
    ScenarioValidationError,
)
from squadopt.scenarios.optimization import optimize_scenario_aware_squad
from squadopt.scenarios.paths import (
    SCENARIO_PATH_CONTRACT_VERSION,
    ScenarioPathSet,
    ScenarioPathTarget,
    generate_scenario_paths,
)
from squadopt.scenarios.rank import (
    CLAIM_SCENARIO_MODES,
    RANK_OBJECTIVE_CONTRACT_VERSION,
    GoalMenuEntry,
    RankObjectiveConfig,
    RankOptimizationResult,
    goal_menu,
    optimize_rank_probability_squad,
)
from squadopt.scenarios.reporting import (
    scenario_result_to_dict,
    scenario_result_to_markdown,
)
from squadopt.scenarios.rivals import (
    TEMPLATE_RIVAL_CONTRACT_VERSION,
    template_rival_diagnostics,
    template_rival_from_ownership,
)

__all__ = [
    "CLAIM_SCENARIO_MODES",
    "COMPONENT_DECISION_LOWER_QUANTILE",
    "COMPONENT_DECISION_READOUT_CONTRACT_VERSION",
    "COMPONENT_DECISION_SCORING_CONTRACT_VERSION",
    "RANK_OBJECTIVE_CONTRACT_VERSION",
    "RESIDUAL_HISTORY_COLUMNS",
    "SCENARIO_CONTRACT_VERSION",
    "SCENARIO_EVALUATION_CONTRACT_VERSION",
    "SCENARIO_OPTIMIZATION_CONTRACT_VERSION",
    "SCENARIO_PATH_CONTRACT_VERSION",
    "TEMPLATE_RIVAL_CONTRACT_VERSION",
    "ComponentDecisionDistributionReadout",
    "ComponentDecisionScoringResult",
    "GoalMenuEntry",
    "RankObjectiveConfig",
    "RankOptimizationResult",
    "RivalSquad",
    "ScenarioComparisonResult",
    "ScenarioConfig",
    "ScenarioConfigurationError",
    "ScenarioError",
    "ScenarioEvaluationConfig",
    "ScenarioEvaluationResult",
    "ScenarioOptimizationConfig",
    "ScenarioOptimizationResult",
    "ScenarioPathSet",
    "ScenarioPathTarget",
    "ScenarioRiskMetrics",
    "ScenarioSet",
    "ScenarioTarget",
    "ScenarioValidationError",
    "compare_fixed_decisions",
    "evaluate_fixed_decision",
    "generate_scenario_paths",
    "generate_scenarios",
    "goal_menu",
    "optimize_rank_probability_squad",
    "optimize_scenario_aware_squad",
    "scenario_result_to_dict",
    "scenario_result_to_markdown",
    "score_component_scenario_decision",
    "summarize_component_decision_distribution",
    "template_rival_diagnostics",
    "template_rival_from_ownership",
    "validate_residual_history",
    "wilson_interval",
]
