"""Constrained starting elevens and paired substitutions for contextual match worlds.

This is an explicit conditional-lineup approximation, not a fitted substitution hazard.
One goalkeeper and legal 3..5/2..5/1..3 outfield formations start. At most five paired
changes preserve eleven occupied places and exactly 990 regulation player-minutes.
Red-card match paths are not generated by this approximation.
"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt
import pandas as pd

Array = npt.NDArray[np.float64]


def _partition(weights: Array, size: int) -> Array:
    """Elementary symmetric polynomials for a conditional Bernoulli sample."""
    table = np.zeros((len(weights) + 1, size + 1))
    table[:, 0] = 1
    for i, weight in enumerate(weights, 1):
        for k in range(1, min(i, size) + 1):
            table[i, k] = table[i - 1, k] + weight * table[i - 1, k - 1]
    return table


def _subset(weights: Array, size: int, rng: np.random.Generator) -> list[int]:
    table = _partition(weights, size)
    if table[-1, size] <= 0:
        raise ValueError("No eligible legal lineup for the supplied roster.")
    selected = []
    remaining = size
    for i in range(len(weights), 0, -1):
        if remaining == 0:
            break
        probability = weights[i - 1] * table[i - 1, remaining - 1] / table[i, remaining]
        if rng.random() < probability:
            selected.append(i - 1)
            remaining -= 1
    return selected


def _starting_xi(group: pd.DataFrame, rng: np.random.Generator) -> list[int]:
    probabilities = group.start_probability.to_numpy(float)
    appeared = group.appearance_probability.to_numpy(float)
    if (
        not np.isfinite(probabilities).all()
        or not np.isfinite(appeared).all()
        or (probabilities < 0).any()
        or (probabilities > appeared + 1e-12).any()
        or (appeared > 1).any()
    ):
        raise ValueError("Start/appearance probabilities are inconsistent.")
    certain = probabilities == 1
    weights = np.where(certain, 0, probabilities / np.maximum(1 - probabilities, 1e-6))
    # A common scale cancels conditional on selecting eleven and avoids large products.
    weights /= max(float(weights.max()), 1.0)
    positions = group.position.to_numpy()
    indices = {pos: np.flatnonzero(positions == pos) for pos in ("GK", "DEF", "MID", "FWD")}
    masses = {pos: _partition(weights[ix], 5)[-1] for pos, ix in indices.items()}
    formations = []
    likelihoods = []
    for defenders in range(3, 6):
        for midfielders in range(2, 6):
            forwards = 10 - defenders - midfielders
            if 1 <= forwards <= 3:
                formation = (1, defenders, midfielders, forwards)
                likelihood = float(
                    np.prod(
                        [
                            masses[pos][count - int(certain[indices[pos]].sum())]
                            if count >= int(certain[indices[pos]].sum())
                            else 0
                            for pos, count in zip(indices, formation, strict=True)
                        ]
                    )
                )
                if likelihood > 0:
                    formations.append(formation)
                    likelihoods.append(likelihood)
    if not likelihoods or not np.isfinite(likelihoods).all():
        raise ValueError("Joint football worlds require a complete eligible club roster.")
    law = np.asarray(likelihoods)
    formation = formations[int(rng.choice(len(formations), p=law / law.sum()))]
    starters = [int(i) for i in np.flatnonzero(certain)]
    for pos, count in zip(indices, formation, strict=True):
        ix = indices[pos]
        remaining = count - int(certain[ix].sum())
        starters.extend(int(ix[i]) for i in _subset(weights[ix], remaining, rng))
    return starters


def sample_intervals(group: pd.DataFrame, rng: np.random.Generator) -> tuple[Array, Array]:
    """Condition on legal XI/substitution capacity; preserve hard absence/minute limits.

    Bounded rejection conditions the XI on sufficient eligible like-for-like replacements
    for explicitly limited starters. This changes marginals and must be measured, not
    described as calibration. Unsupported rosters fail instead of relaxing evidence.
    """
    positions = group.position.to_numpy()
    appeared = group.appearance_probability.to_numpy(float)
    probabilities = group.start_probability.to_numpy(float)
    limited = (
        group.minutes_limited.to_numpy(bool)
        if "minutes_limited" in group
        else np.zeros(len(group), dtype=bool)
    )
    if "minutes_limited" in group and not group.minutes_limited.isin((True, False)).all():
        raise ValueError("Minute limits must be categorical.")
    for _ in range(128):
        starters = _starting_xi(group, rng)
        forced_out = [i for i in starters if limited[i]]
        if len(forced_out) > 5:
            continue
        if all(
            sum(positions[i] == pos for i in forced_out)
            <= sum(
                positions[i] == pos and appeared[i] > 0
                for i in range(len(group))
                if i not in starters
            )
            for pos in ("GK", "DEF", "MID", "FWD")
        ):
            break
    else:
        raise ValueError("No supported lineup with feasible explicit minute limits in 128 draws.")
    start = np.zeros(len(group))
    end = np.zeros(len(group))
    end[starters] = 90
    on_pitch = set(starters)
    unused = [i for i in range(len(group)) if i not in on_pitch]
    # Conditional cameo chances; the five-change capacity couples otherwise eligible subs.
    cameo = np.divide(
        np.maximum(appeared - probabilities, 0),
        1 - probabilities,
        out=np.zeros(len(group)),
        where=probabilities < 1,
    )
    rng.shuffle(unused)
    changes = 0
    # Hard source constraints take precedence over optional substitutions.
    for leaving in forced_out:
        candidates = [i for i in unused if positions[i] == positions[leaving] and appeared[i] > 0]
        weights_in = appeared[candidates]
        incoming = int(rng.choice(candidates, p=weights_in / weights_in.sum()))
        values = group.iloc[leaving][["minute_value_1", "minute_value_2"]].to_numpy(float)
        law = group.iloc[leaving][["minute_probability_1", "minute_probability_2"]].to_numpy(float)
        if law.sum() <= 0:
            raise ValueError("A minute-limited starter requires learned sub-90 support.")
        time = int(np.clip(np.rint(rng.choice(values, p=law / law.sum())), 1, 89))
        end[leaving] = time
        start[incoming], end[incoming] = time, 90
        unused.remove(incoming)
        on_pitch.remove(leaving)
        changes += 1
    for incoming in unused:
        if changes == 5 or rng.random() >= cameo[incoming]:
            continue
        # Like-for-like changes preserve the sampled formation. No GK/outfield swap.
        outgoing = [i for i in starters if i in on_pitch and positions[i] == positions[incoming]]
        if not outgoing:
            continue
        weights_out = np.maximum(1 - group.minute_probability_3.to_numpy(float)[outgoing], 1e-6)
        leaving = int(rng.choice(outgoing, p=weights_out / weights_out.sum()))
        # Existing learned sub-90 minute support gives an auditable timing prior.
        values = group.iloc[leaving][["minute_value_1", "minute_value_2"]].to_numpy(float)
        law = group.iloc[leaving][["minute_probability_1", "minute_probability_2"]].to_numpy(float)
        time = int(
            np.clip(np.rint(rng.choice(values, p=law / law.sum()) if law.sum() > 0 else 75), 1, 89)
        )
        end[leaving] = time
        start[incoming], end[incoming] = time, 90
        on_pitch.remove(leaving)
        changes += 1
    return start, end
