"""Generate the packaged Python stems from the shared plain-string contract.

The web imports the JSON directly. Python ships this generated constant so an installed
wheel never needs a source checkout's docs directory. The contract test rejects drift.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    contract = json.loads((ROOT / "docs/contracts/honesty_words.json").read_text(encoding="utf-8"))
    lines = [
        '"""Generated by scripts/generate_honesty_stems.py; do not edit."""',
        "",
        "from typing import Final",
        "",
    ]
    for language, stems in contract["stems"].items():
        lines.append(f"{language.upper()}_STEMS: Final = (")
        lines.extend(f"    {json.dumps(stem)}," for stem in stems)
        lines.append(")")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    (ROOT / "src/squadopt/contracts/honesty_stems.py").write_text(render(), encoding="utf-8")
