"""Runtime platform contracts above the transport-neutral application layer.

This package may consume ``squadopt.application`` and every lower engine layer. Nothing
below it imports platform code. The concrete HTTP adapter lives above this package in
``squadopt.api``; database, queue and deployment adapters remain future work on the same
side of the boundary.
"""

from squadopt.platform.api_contract import (
    BACKEND_API_CONTRACT_VERSION,
    BACKEND_API_SCHEMA_PATH,
    BACKEND_API_VERSION,
    ApiCommandRequest,
    ApiError,
    ApiErrorResponse,
    ApiOperation,
    ApiRunResponse,
    ApiRunStatus,
    ApiServiceInfo,
    BackendApiContractError,
    backend_api_schema,
    serialize_api_document,
    write_backend_api_schema,
)
from squadopt.platform.artifacts import (
    ARTIFACT_RECORD_CONTRACT_VERSION,
    ARTIFACT_RECORD_DIRECTORY,
    ARTIFACT_RECORD_SCHEMA_PATH,
    ArtifactIntegrityError,
    ArtifactLineage,
    ArtifactNotFoundError,
    ArtifactRecord,
    ArtifactRecordError,
    ArtifactRegistryError,
    ArtifactRole,
    FileArtifactRegistry,
    artifact_checksum,
    artifact_record_schema,
    build_artifact_id,
    parse_artifact_record,
    serialize_artifact_record,
    write_artifact_record_schema,
)
from squadopt.platform.context import (
    RUN_CONTEXT_CONTRACT_VERSION,
    RunContext,
    RunContextError,
)
from squadopt.platform.manifest import (
    RUN_MANIFEST_CONTRACT_VERSION,
    RUN_MANIFEST_SCHEMA_PATH,
    RunManifestError,
    parse_run_manifest,
    read_run_manifest,
    run_manifest_document,
    run_manifest_schema,
    serialize_run_manifest,
    write_run_manifest,
    write_run_manifest_schema,
)
from squadopt.platform.queries import (
    JsonDocument,
    PublishedViewError,
    PublishedViewIntegrityError,
    PublishedViewNotFoundError,
    PublishedViewStore,
)
from squadopt.platform.runtime import (
    RuntimeArtifact,
    RuntimeContractError,
    RuntimeEventSink,
    RuntimeFailure,
    RuntimeInputArtifact,
    RuntimeOperationResult,
    RuntimePhase,
    RuntimePreparationError,
    RuntimeRequest,
    RuntimeResult,
    RuntimeRunner,
    RuntimeStatus,
)

__all__ = [
    "ARTIFACT_RECORD_CONTRACT_VERSION",
    "ARTIFACT_RECORD_DIRECTORY",
    "ARTIFACT_RECORD_SCHEMA_PATH",
    "BACKEND_API_CONTRACT_VERSION",
    "BACKEND_API_SCHEMA_PATH",
    "BACKEND_API_VERSION",
    "RUN_CONTEXT_CONTRACT_VERSION",
    "RUN_MANIFEST_CONTRACT_VERSION",
    "RUN_MANIFEST_SCHEMA_PATH",
    "ApiCommandRequest",
    "ApiError",
    "ApiErrorResponse",
    "ApiOperation",
    "ApiRunResponse",
    "ApiRunStatus",
    "ApiServiceInfo",
    "ArtifactIntegrityError",
    "ArtifactLineage",
    "ArtifactNotFoundError",
    "ArtifactRecord",
    "ArtifactRecordError",
    "ArtifactRegistryError",
    "ArtifactRole",
    "BackendApiContractError",
    "FileArtifactRegistry",
    "JsonDocument",
    "PublishedViewError",
    "PublishedViewIntegrityError",
    "PublishedViewNotFoundError",
    "PublishedViewStore",
    "RunContext",
    "RunContextError",
    "RunManifestError",
    "RuntimeArtifact",
    "RuntimeContractError",
    "RuntimeEventSink",
    "RuntimeFailure",
    "RuntimeInputArtifact",
    "RuntimeOperationResult",
    "RuntimePhase",
    "RuntimePreparationError",
    "RuntimeRequest",
    "RuntimeResult",
    "RuntimeRunner",
    "RuntimeStatus",
    "artifact_checksum",
    "artifact_record_schema",
    "backend_api_schema",
    "build_artifact_id",
    "parse_artifact_record",
    "parse_run_manifest",
    "read_run_manifest",
    "run_manifest_document",
    "run_manifest_schema",
    "serialize_api_document",
    "serialize_artifact_record",
    "serialize_run_manifest",
    "write_artifact_record_schema",
    "write_backend_api_schema",
    "write_run_manifest",
    "write_run_manifest_schema",
]
